- Cargo.toml
By default the `c-kzg` dep on revm is enabled, and we don't need this for the inspectors, so we can disable it.
this also should fix the [release workflow failures for linux](https://github.com/foundry-rs/foundry/actions/runs/7508860860) on foundry.
> chore(`deps`): disable default features for `revm`

- src/tracing/js/bindings.rs
- src/tracing/js/mod.rs
closes #3
introduces a container type for the additional tx context that's made available to the JS tracer
> feat: add TransactionContext type

- src/tracing/js/mod.rs
> fix: apply runtime limits

- Cargo.toml
- src/tracing/js/bindings.rs
- src/tracing/js/builtins.rs
- src/tracing/js/mod.rs
Closes #6
This gets rid of the additional JS service requirement by transmuting the db reference and guarding it against garbage collection.
This applies a similar transmute hack as `std::thread::scoped` by transmuting the lifetime bound of the DB via a trait object.
The DB wrappers are nullable, once the guard is dropped the actual garbage collected DB reference is also removed
> feat: use inspector db directly in js

- src/tracing/builder/geth.rs
- src/tracing/types.rs
Closes #13
~~This could potentially be simplified if we can simply use the result's statediff if this has the initial value for modified slots and not just the previous~~
because the prestate tracer should only include changed slots:
https://github.com/ethereum/go-ethereum/blob/bc0b87ca196f92e5af49bd33cc190ef0ec32b197/eth/tracers/native/prestate.go#L216-L224
simplifies prestate result by only checking changed accounts and using the original value
cc @rakita
> fix: use original value in prestate tracer

- src/tracing/types.rs
Exposes a few extra functions in CallTraceNode so that they're public to users of the crate rather than just internally. (In case someone wants to make parity or geth-like traces
> change: Expose additional fields

- src/tracing/builder/geth.rs
prestate tracer should include all slots and don't do any cleanup because cleanup skipped if not diffmode:
https://github.com/ethereum/go-ethereum/blob/fc380f52ef9778e988266f776b9593ce719cf79d/eth/tracers/native/prestate.go#L187-L189
ref 
https://github.com/paradigmxyz/reth/issues/6429
> fix: prestate tracer

- Cargo.toml
Reverts paradigmxyz/evm-inspectors#8
they don't need to be locked
this will be a nightmare to maintain
> Revert "dep: lock alloy deps"

- Cargo.toml
rm redundant lint https://github.com/paradigmxyz/evm-inspectors/actions/runs/7855531397/job/21437338557#step:5:19
```
error: lint group `rust_2018_idioms` has the same priority (0) as a lint
--> Cargo.toml:19:6
|
18 | rust.unused_must_use = "deny"
|      --------------- has the same priority as this lint
19 | rust.rust_2018_idioms = "deny"
|      ^^^^^^^^^^^^^^^^   ------ has an implicit priority of 0
```
> chore(clippy): make clippy happy

- src/tracing/types.rs
- tests/it/main.rs
- tests/it/parity.rs
- tests/it/utils.rs
Closes #21
TLDR selfdestruct in constructor is not recorded as `InstructionResult::Selfdestruct`
this uses the refund target to identify selfdestructs
> fix: record CREATE + SELFDESTRUCT

- src/access_list.rs
- src/opcode.rs
- src/stack/maybe_owned.rs
- src/stack/mod.rs
- src/tracing/arena.rs
- src/tracing/config.rs
- src/tracing/fourbyte.rs
- src/tracing/js/bindings.rs
- src/tracing/types.rs
`cargo clippy --workspace --all-features --fix -- -Wclippy::use_self && cargo fmt`. NFC
> chore: fix `clippy::use_self`

- src/access_list.rs
- src/opcode.rs
- src/stack/mod.rs
- src/tracing/arena.rs
- src/tracing/config.rs
- src/tracing/fourbyte.rs
- src/tracing/js/bindings.rs
- src/tracing/js/builtins.rs
- src/tracing/js/mod.rs
- src/tracing/mod.rs
- src/tracing/opcount.rs
- src/tracing/types.rs
> chore: sort derives

- src/tracing/types.rs
All the fields are set to `Default::default()`. NFC
> chore: derive Default for CallTrace

- src/stack/maybe_owned.rs
> chore: rename inspector generics

- Cargo.toml
- src/tracing/arena.rs
- src/tracing/types.rs
Ref https://github.com/foundry-rs/foundry/issues/6922
> feat: add feature-gated Serde implementations

- Cargo.toml
Updates `alloy-rpc-types` and `alloy-rpc-trace-types` to `76c70fb9d44ace661bbf33408c2527e3874c964e`, which contains https://github.com/alloy-rs/alloy/pull/227
> feat: bump alloy rpc types rev

- src/tracing/mod.rs
this is a leftover of #11 
@rakita 
the `output` of `CreateOutcome` is the runtime bytecode, right?
https://github.com/paradigmxyz/evm-inspectors/blob/05352cd16db13fd89e9a974487b456e3f1498c69/src/tracing/types.rs#L48-L50
> chore: remove unused code var

- Cargo.toml
- src/tracing/mod.rs
- src/tracing/mux.rs
- tests/it/geth.rs
Adds support for `muxTracer`. Depends on changes from https://github.com/alloy-rs/alloy/pull/252
Once both PR's are good to go I'll open a PR also for `reth`.
> feat(tracing): implement muxTracer

- src/tracing/config.rs
- src/tracing/mux.rs
blocked by https://github.com/bluealloy/revm/pull/1174
the `GethDefaultTracingOptions` dont have any effect on the call and prestate tracer
this adds special functions for those tracers.
The prestate tracer can be simplified entirely and doesn't even have to be a tracer I think, but need to handle that separately
> feat: more geth tracer config functions

- src/tracing/js/bindings.rs
- src/tracing/js/builtins.rs
- src/tracing/js/mod.rs
closes #69
closes https://github.com/paradigmxyz/reth/issues/7083
use builtin JSON.stringify when formatting the result, boa.to_json uses all properties
> fix: use JSON.stringify for JS result

- src/lib.rs
- src/transfer.rs
- tests/it/main.rs
- tests/it/transfer.rs
This can be used by `ots_getInternalOperations` to trace internal eth transfers
ref https://github.com/ledgerwatch/erigon/blob/aefb97b07d1c4fd32a66097a24eddd8f6ccacae0/turbo/jsonrpc/otterscan_trace_operations.go#L42-L55
> feat: add transferinspector

- Cargo.toml
Alloy deps need to be bumped in https://github.com/foundry-rs/foundry/pull/7619. This creates a conflicting deps version between `evm-inspectors` and `foundry` for `alloy-rpc-types` and `alloy-rpc-types-trace`
Bump to latest alloy commit
> bump alloy rpc deps

- Cargo.toml
Updates to https://github.com/alloy-rs/core/releases/tag/v0.7.1
Required for Foundry's update to Alloy
> chore(deps): bump to alloy-core to `0.7.1` and alloy to `98da8b8`

- Cargo.toml
required for https://github.com/foundry-rs/foundry/issues/7867
also includes new fn for https://github.com/paradigmxyz/reth/pull/7993
cc @fgimenez
> chore: bump alloy 17c5650

- src/tracing/mod.rs
- src/tracing/types.rs
- tests/it/parity.rs
In >=Cancun `selfdestruct` inspector function is not called, but `SELFDESTRUCT` is still returned as instruction result.
Found while debugging https://github.com/foundry-rs/foundry/pull/7880
> fix: selfdestructs once and for all

- src/tracing/arena.rs
- tests/it/geth.rs
Fixes out of bound error when using `fuse()` in `TracingInspector`.
Error before:
```
index out of bounds: the len is 0 but the index is 0
panicked at src/tracing/arena.rs:54:31:
```
Cause: `CallTraceArena` is initialized using `default()` but when calling `clear()` the default root node is removed.
> Fix index out of bound when resetting TracingInspector

- Cargo.toml
- src/tracing/builder/geth.rs
- src/tracing/builder/parity.rs
- src/tracing/js/bindings.rs
Bump to newest revm, some structs were renamed
> chore: bump revm

- src/tracing/js/bindings.rs
- src/tracing/js/builtins.rs
closes https://github.com/paradigmxyz/reth/issues/8103
previously we were using the ArrayBuffer incorrectly, we need to use `JsUint8Array`
see also geth:
https://github.com/ethereum/go-ethereum/blob/473ee8fc07a3f89cf3978e164a6fad218de9a6b5/eth/tracers/js/goja.go#L575-L579
> fix: use JsUint8Array for buffers

- Cargo.toml
- src/tracing/mod.rs
- src/tracing/types.rs
Upgrade revm version to help unblock changes needed in https://github.com/paradigmxyz/reth/pull/8264#discussion_r1641852772
> chore: Upgrade revm version

- src/tracing/arena.rs
- src/tracing/mod.rs
- src/tracing/types.rs
- src/tracing/writer.rs
Adds `Step` variant for `LogCallOrder` enum and renames it to `TraceMemberOrder`.
This is useful for printing logic which relies on execution steps as well, e.g. https://github.com/foundry-rs/foundry/pull/8222
> feat: Add `Step` to `LogCallOrder`

- src/tracing/config.rs
- src/tracing/mod.rs
- src/tracing/types.rs
- Adds `record_returndata_snapshots` flag to config which enables snapshots of `interpreter.return_data_buffer`
- Adds `record_opcodes_filter` parameter which allows to only record specific opcodes. ref https://github.com/foundry-rs/foundry/pull/8222#issuecomment-2186811858
- Adds `gas_used` field for `CallTraceStep`
This should be enough to migrate foundry's debugger to using `TracingInspector` from here, I will open PR for this later today.
> feat: small updates for steps tracing

- src/tracing/mod.rs
- src/tracing/types.rs
- tests/it/parity.rs
in https://github.com/paradigmxyz/revm-inspectors/commit/ee6f6be412c61a494472468c37bc7b8bc292b458 we updated
`node.trace.value = value;` with the selfdestruct value transfer.
this results in incorrect traces for original call: https://github.com/paradigmxyz/reth/issues/9124
This tracks the transferred value in a separate field similar to refund address.
> fix: track selfdestruct transferred value separately

- src/tracing/mod.rs
- src/tracing/types.rs
- src/tracing/writer.rs
- tests/it/writer.rs
ref https://github.com/foundry-rs/foundry/pull/8222
ref https://github.com/foundry-rs/foundry/issues/8198
Adds structs and extends `TraceWriter` to support formatting of decoded trace steps. Currently two decoding formats are supported:
- Internal calls. Similar to a decoded call trace, decoded internal function invocation which spans over multiple steps. Kept as decoded function name, inputs, outputs and index of the last step.
- Arbitrary strings. This might be useful for formatting decoded opcodes (e.g. adding `├─ [sload] <slot>` to trace. It might make sense to extend it to something more configurable once we start implementing this
> feat: add decoding for individual trace steps

- src/opcode.rs
- src/tracing/builder/parity.rs
- src/tracing/mod.rs
Those are now available as `OpCode` methods
> refactor: prefer using revm helpers

- src/opcode.rs
- src/tracing/config.rs
- src/tracing/mod.rs
- src/tracing/types.rs
before EOF those were only present for `PUSH*` opcodes, and they were trivial to obtain by looking at the top of the stack, now it is a bit more complex, so this would be useful
> feat: add immediate bytes recording

- src/tracing/builder/parity.rs
The `suicide`/`selfdestruct` trace should not be immediately after the parent trace but after all of the parent's subtraces.
This can be fixed by ordering the `traces` using the attribute `trace_address` inside.
closes https://github.com/paradigmxyz/revm-inspectors/issues/162
> Fix Self-destruct Disorder

- src/tracing/builder/geth.rs
- src/tracing/types.rs
The inconsistent problem in getting the Geth Debug trace result of a transaction
which includes a `suicide` / `selfdestruct` call type.
With the latest version reth v1.0.3, using `debug_traceTransaction()` and `callTracer` to trace
the transaction `0x47e9962fec372e5c34e650cbd094e396fe6278cd7b0ee5d34bccfe2739809e9c`
```
curl http://localhost:8545 \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"debug_traceTransaction","params":["0x47e9962fec372e5c34e650cbd094e396fe6278cd7b0ee5d34bccfe2739809e9c", {"tracer": "callTracer"}], "id":1,"jsonrpc":"2.0"}'
```
**From Reth**
which is a two-layer nested structure, and  
the `from` field  of `SELFDESTRUCT` call is `0x322237f0f8d0cf75c413d76fbbbb658cd2edf7c1`
```
{'calls': [{'from': '0x322237f0f8d0cf75c413d76fbbbb658cd2edf7c1', …
```
> fix: geth trace inconsistence with selfdestruct

- src/tracing/js/bindings.rs
- src/tracing/js/mod.rs
- src/tracing/mod.rs
Closes https://github.com/paradigmxyz/revm-inspectors/issues/182
> Move TransactionContext from js to tracing

- Cargo.toml
- src/tracing/js/mod.rs
> chore: pin intrusive collections

- src/tracing/builder/parity.rs
because the selfdestruct doesn't have separate trace, if will returned just after the original call, this is inaccure, and we should keep them staying at the ending of the same call depth.
> fix(tracing/builder): ensure the selfdestruct trace is at the ending of the same depth

- src/tracing/builder/parity.rs
- src/tracing/types.rs
Some small optimizes:
- early return for StateDiff-only requests
- early check `if with_traces` instead of inside the for-loop
- for trace address use `Vec::with_capacity(n+1)` instead of `clone`
> feat(tracing/builder): optimize the trace builder

- src/transfer.rs
ref https://github.com/ethereum/execution-apis/pull/484 https://github.com/paradigmxyz/reth/pull/10829
Also added hook for `eofcreate` and moved all handling away from `_env` hooks to ensure correct ordering.
We don't yet insert logs for selfdestructs, would need update on revm side to pass journaled state into the hook
> feat: add helper for eth_simulateV1 to `TransferInspector`

- src/tracing/types.rs
1. The error msg should not be converted to parity style in `callTracer`. They should only be converted in `flatCallTracer` which is not supported by reth now.
2. The `gasUsed` should be the `gasLimit` when there's a not reverted error.
3. The `call_frame.to` should be None if the call type is `Create/Create2` and it failed.
Related geth code: 
* https://github.com/ethereum/go-ethereum/blob/a9523b6428238a762e1a1e55e46ead47630c3a23/eth/tracers/native/call_flat.go#L226
* https://github.com/ethereum/go-ethereum/blob/a9523b6428238a762e1a1e55e46ead47630c3a23/core/vm/evm.go#L254
* https://github.com/ethereum/go-ethereum/blob/a9523b6428238a762e1a1e55e46ead47630c3a23/eth/tracers/native/call.go#L88
> fix(tracing): align trace output with geth

- src/tracing/config.rs
For use and uniformity wrt https://github.com/paradigmxyz/reth/issues/10991
Simple tests included
I could do the PR without this but seems correct to maintain uniformity instead of modifying the `TracingInspector` in ad hoc ways
> chore: add `from_flat_call_config`

- src/tracing/types.rs
Return a detailed OOG error, require https://github.com/bluealloy/revm/pull/1795 to be released first. ref https://github.com/ethereum/go-ethereum/pull/29354
> chore(tracing): return detailed oog message

- src/tracing/js/bindings.rs
distinguish the error of stack size out of bound or stake is null.
> tracing/js: distinguish stack oob error

- src/tracing/js/mod.rs
fix a copy/paste error, checking `fault_fn` but used `result_fn`
> fix(tracing/js): fault_fn not checked

- src/tracing/js/bindings.rs
- src/tracing/js/mod.rs
- tests/it/geth.rs
We only set step's error, but missing the result's one. 
use this tx to test it
```json
{
"jsonrpc": "2.0",
"method": "debug_traceTransaction",
"id": "1",
"params": [
"0x18ba7c5bcb851072612c0451377f55ac4ef83986ec8d9f87a2ce07c9a7d6371f", 
{
"tracer": "{ fault: function() {}, result: function(ctx, _) { return { error: !!ctx.error }; } }"
}
]
}
```
for geth/erigon's response is:
```json
{
"id": "1",
"jsonrpc": "2.0",
"result": {
"error": true
}
}
```
currently reth's response is:
```json
{
"id": "1",
"jsonrpc": "2.0",
"result": {
"error": false
}
}
```
> fix(tracing/js): error not set in result_fn

- src/tracing/js/bindings.rs
- src/tracing/js/mod.rs
- src/tracing/mod.rs
add `coinbase` into js-tracer's context, backport https://github.com/ethereum/go-ethereum/pull/30231
> feat(tracing): js-tracer add coinbase into context

- tests/it/geth.rs
- tests/it/geth_js.rs
- tests/it/main.rs
Move js tracer tests into a `geth_js` module, so no need to add `#[cfg(feature = "js-tracer")]` for each js tracer tests.
> chore(tests): move js tracer into a single module

- src/tracing/js/builtins.rs
- tests/it/geth.rs
1. go-ethereum/erigon's `toHex` returns with `0x` prefix(ref https://github.com/ethereum/go-ethereum/blob/fad7e74a1b2995dd79002c184e532eff31382579/eth/tracers/js/goja.go#L467), we should keep the same;
2. add more unit tests for the builtin functions.
> fix(tracing/js): toHex returns with 0x as prefix

- src/tracing/js/bindings.rs
Seems we're using the opposite judge logic to check the ending and memory length. found in https://github.com/paradigmxyz/revm-inspectors/actions/runs/11389609241/job/31689313431?pr=231
> fix(js): the opposite checking logic

- src/tracing/config.rs
- src/tracing/mod.rs
Add "StackSnapshotType::All" for easier reading of trace steps, as shown in the picture.
> feat: StackSnapshotType (All).

- src/tracing/types.rs
- tests/it/parity.rs
waiting for https://github.com/alloy-rs/alloy/pull/1621
> feat(trace/parity): add  trace creation method

- src/tracing/js/mod.rs
- tests/it/geth_js.rs
fixes https://github.com/paradigmxyz/reth/issues/13089
btw, this PR also fixes the incorrect caller address in delegatecall.
> fix(js): incorrect caller and contract address extracting

- .gitignore
- src/edge_cov.rs
- src/lib.rs
- tests/it/edge_cov.rs
- tests/it/main.rs
For use in Foundry coverage guided fuzzing. I think the other functionality such as [comparing two edge maps](https://github.com/h0mbre/Lucid/blob/3026e7323c52b30b3cf12563954ac1eaa9c6981e/src/coverage.rs#L72) can be added later or in Foundry directly
> feat: add edge coverage tracking inspired by AFL/Lucid

- src/access_list.rs
Right now caller is required to provide `AccessListInspector` with the list of precompiles which is unnecessary and requires caller to peek into EVM internals. Besides making API more complex this also results in reth not excluding p256 OP precompile when preparing access list https://github.com/paradigmxyz/reth/blob/890507a98adef94b3970312ef796eb40f87206df/crates/rpc/rpc-eth-api/src/helpers/call.rs#L430-L431
This PR changes `AccessListInspector` to obtain `from`, `to` and `precompiles` from the top-level frame and not requiring caller to provide anything
> feat: simplify AccessListInspector API

- src/tracing/js/mod.rs
`self.enter_fn.is_some()` is used in the `can_call_exit` method to check for the presence of an entry function (`enter_fn`). This is incorrect, as the method should be checking for the exit function (`exit_fn`).
I've fixed this by updating the check to `self.exit_fn.is_some()`. This aligns with the method's intended behavior.
> chore: Fix incorrect function check in mod.rs

- src/tracing/mux.rs
- src/tracing/utils.rs
- src/transfer.rs
- **Old:** `/// A instance of FourByteInspector that can be reused`
- **New:** `/// An instance of FourByteInspector that can be reused`
- **Reason:** Corrected the grammatical error by changing "A" to "An" to ensure proper article usage before a vowel sound.
- **Old:** `/// Returns a non empty revert reason if the output is a revert/error.`
- **New:** `/// Returns a non-empty revert reason if the output is a revert/error.`
- **Reason:** Added a hyphen to "non-empty" to correctly form the compound adjective, improving clarity and grammatical accuracy.
- **Old:** `/// A non zero value transfer CALL`
- **New:** `/// A non-zero value transfer CALL`
- **Reason:** Added a hyphen to "non-zero" to correctly form the compound adjective, enhancing clarity and grammatical correctness.
These changes …
> Grammar and Clarity Improvements in Code Comments

- src/tracing/types.rs
closes #264 
closes https://github.com/paradigmxyz/reth/issues/14779
> added additional match arm for OutOfFunds

- src/edge_cov.rs
closes https://github.com/paradigmxyz/revm-inspectors/issues/271
h/t @MiloTruck
> fix: reversed JUMPI args

- src/tracing/builder/parity.rs
- tests/it/parity.rs
closes https://github.com/paradigmxyz/reth/issues/15150
the bug here was that we didn't record all selfdestructs and replaced previous ones (higher address) if there was another selfdestruct.
this fixes this by recording selfdestructs in a stack
> fix: populate selfdestructs in localized parity

- src/tracing/mod.rs
closes https://github.com/paradigmxyz/reth/issues/15237
prevents the underflow by using saturing sub instead
> fix: use saturating sub for push stack calc

- src/tracing/js/mod.rs
> Remove DatabaseCommit requirement from JsInspector ContextTr

- src/access_list.rs
Since there is no way to access the internal map, this PR introduces a `fn touched_slots`. To avoid conflicting with the semantics of `fn access_list`, I named it `touched_slots`. The reason for this is that using the map speeds up the process of checking whether certain slots have been touched.
> chore(access-list): Add function to access touched slots

- src/tracing/fourbyte.rs
When using revm-inspectors as a dependency in my project, I encountered the following compilation error:
```
error[E0277]: the trait bound `[u8]: AsRef<[_; 0]>` is not satisfied
--> /home/cheddie/.cargo/git/checkouts/revm-inspectors-c863f094e4c77dd4/9fe2ce1/src/tracing/fourbyte.rs:55:31
|
55 | ...                   r.as_ref()
|                         ^^^^^^ the trait `AsRef<[_; 0]>` is not implemented for `[u8]`
|
= help: the following other types implement trait `AsRef<T>`:
`[u8]` implements `AsRef<winnow::stream::bstr::BStr>`
`[u8]` implements `AsRef<winnow::stream::bytes::Bytes>`
```
After this fix, the crate compiles successfully when used as a dependency.
I'm happy to make any adjustments if there's a more idiomatic way to handle this conversion.
> fix: correct Ref<[u8]> to &[u8] conversion in FourByteInspector

- Cargo.toml
Bumps Revm to 24.0.0
New releases are out: https://github.com/bluealloy/revm/releases/tag/v74
Required for https://github.com/foundry-rs/foundry/issues/10557
> chore(`deps`): bump revm to 24.0.0

- src/tracing/arena.rs
prep for https://github.com/foundry-rs/foundry/pull/10596
> chore: add trace_addresses helper

- src/tracing/config.rs
the vmtracer needs state diffs for
https://github.com/alloy-rs/alloy/blob/c808022d571aaffb97a3429a0fdba6fc06e8f7aa/crates/rpc-types-trace/src/parity.rs#L659-L660
so that we enter here:
https://github.com/paradigmxyz/revm-inspectors/blob/1c0e405ad008453cded08b44a3cfa2ca611a6aa8/src/tracing/mod.rs#L502-L502 and record the `step-storage_change`
https://github.com/paradigmxyz/revm-inspectors/blob/1c0e405ad008453cded08b44a3cfa2ca611a6aa8/src/tracing/mod.rs#L507-L507
> fix: record state diffs for vm tracer

- src/tracing/types.rs
Optimizes the `push_steps_on_stack` method to avoid creating a temporary vector allocation.
The previous implementation would:
1. Call `call_step_stack()` which creates a temporary `Vec`
2. Reverse iterate over that vec and extend the deque
The new implementation:
1. Directly extends the deque with reversed steps (without computing `call_child_id`)
2. Iterates over the inserted range in reverse to set `call_child_id` values where needed
> perf: optimize push_steps_on_stack to avoid temporary allocation

- src/tracing/arena.rs
The `vec![]` macro only allocates for the number of elements. In `CallTraceArena::default()`, it only allocates 1, so when growing it the capacity doubles starting at 1, which is pretty inefficient.
> perf: allocate some more initial capacity for CallTraceArena

- Cargo.toml
- src/tracing/js/mod.rs
Currently the revm-inspectors js tracer acts differently from the geth implementation where the `getCost()` function returns the cumulative amount of cost for each step instead of the individual opcode cost. I added a simple function that will store the previous spent value and then use that in the next step to calculate the currect opcode cost.
> feat(js): add logic to count current opcode cost instead of cumulative

- src/tracing/builder/geth.rs
- src/tracing/builder/parity.rs
- src/tracing/mod.rs
- src/tracing/types.rs
Same as https://github.com/paradigmxyz/revm-inspectors/issues/324, plus a few nits.
Reduces the size of `CallTraceStep` from 336 to 216 bytes on 64-bit.
This is a gain overall because the vast majority of steps (>=95%) do not change storage.
> perf: box CallTraceStep::storage_change

- src/tracing/mod.rs
`return_data.buffer()` is `Bytes`. Cheaply clone it instead of creating a new copy.
> perf: re-use returndata buffer

- src/tracing/mod.rs
- src/tracing/types.rs
This stack should always be exactly 1 element, and the context should be the same in both `step` and `step_end`.
This avoids unnecessary memory bandwidth and `arena` access in case of `!record` in the very hot `step` functions.
> perf: remove step_stack

- src/tracing/builder/geth.rs
- src/tracing/types.rs
The Geth trace builder incorrectly sets the same `returnData` value for all opcode steps in a trace, 
using the final call output instead of the step-specific return data buffer state.
Each opcode step should display the return data buffer state
at that specific point in execution.
All opcode steps show the same returnData value - the final output of the entire
call. 
For example, in a Fibonacci contract call that returns 1, every single opcode
step shows:
"returnData": "0x0000000000000000000000000000000000000000000000000000000000000001"
> Fix return data in geth traces
