Cargo.toml
Lock alloy deps to last commit hash.
=> dep: lock alloy deps

Cargo.toml
Reverts paradigmxyz/evm-inspectors#22
=> Revert "Revert "dep: lock alloy deps""

src/tracing/js/bindings.rs
Closes https://github.com/paradigmxyz/reth/issues/6533
=> fix: getPC typo

src/stack/mod.rs
Matches Foundry:
https://github.com/foundry-rs/foundry/blob/8cebc1f581010209eb4aaf325eef3e503d9daba6/crates/evm/evm/src/inspectors/stack.rs#L173-L182
Small breaking change, Reth does not use this macro currently
=> chore: update call_inspectors macro syntax

Cargo.toml, src/stack/maybe_owned.rs, src/stack/mod.rs, src/tracing/fourbyte.rs, src/tracing/js/mod.rs, src/tracing/mod.rs, tests/it/parity.rs, tests/it/utils.rs
new revm release, few smol api changes
=> chore: bump revm

Cargo.toml
rpc changes, need to upstream to reth
=> chore: bump alloy

Cargo.toml, src/tracing/js/mod.rs, src/tracing/mod.rs, src/tracing/types.rs
Opening PR just to check if CI passes
=> bump: revm

src/tracing/arena.rs, src/tracing/mod.rs
prep for making Inspectors reusable for multiple runs
=> chore: add Inspector::fuse

Cargo.toml, src/tracing/builder/geth.rs
=> chore(bump): revm v7.2.0

src/tracing/mod.rs
gas inspector updates on step_end now.
always call it
=> fix: always call gas inspector

src/tracing/js/bindings.rs, src/tracing/mod.rs
this could be an opcode that is manually added to the evm
=> chore: create unknown opcodes as unchecked

src/tracing/js/bindings.rs, src/tracing/mod.rs
ref https://github.com/paradigmxyz/evm-inspectors/pull/88#discussion_r1554979780
=> chore: always use new_unchecked

Cargo.toml
=> bump alloy 8808d21

Cargo.toml
=> chore: bump alloy 4e22b9e

Cargo.toml, src/tracing/writer.rs
=> chore: bump alloy 0bb7604

src/tracing/types.rs
Follow-up to https://github.com/paradigmxyz/evm-inspectors/pull/111
=> docs: update CallTrace

src/tracing/builder/parity.rs, src/tracing/mod.rs, src/tracing/types.rs
Makes https://github.com/paradigmxyz/revm-inspectors/pull/84 worth it, helps with parity memory traces
=> perf: use Bytes in RecordedMemory

src/tracing/builder/parity.rs, tests/it/parity.rs
closes https://github.com/paradigmxyz/reth/issues/8610
LoadedAsNonExisting is the default, we should not treat them as created
=> fix: dont treat non existing accounts as created

src/tracing/mod.rs
Only `gas_inspector.gas_remaining()` was used, which is equivalent to `interp.gas.remaining()` in the context of `step` and `step_end`.
Additionally, mark the internal `on_step` functions as `#[cold]`, as usually these are the cold path for heavy tracing operations or debugging, rather than the common path.
=> perf: remove GasInspector from tracer, optimize step*

src/tracing/config.rs, src/tracing/js/bindings.rs, src/tracing/mod.rs
Pass OpCode by value, add a &mut method
=> chore: improve opcode filter

src/tracing/builder/parity.rs
The inconsistent problem in analysing the Parity state difference of a transaction  
which includes creating a smart contract that already has a balance. 
With the latest version reth v1.0.3, using `trace_replayTransaction()` and `stateDiff` to trace  
the transaction `0x40926f14808e7217827e8ff9492d15d68d84edae76f71db5ab8c70a5664f4720`
```
curl http://localhost:8545 \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"trace_replayTransaction","params":["0x40926f14808e7217827e8ff9492d15d68d84edae76f71db5ab8c70a5664f4720",["stateDiff"]],"id":1,"jsonrpc":"2.0"}'  
```
The state difference of the newly created smart contract `0xc2d517963c616ee780e833a5318413242a790f08`
**From Reth**
```
"0xc2d517963c616ee780e833a5318413242a790f08": {
"balance": {
"+": "0x0"
},
"code": {
"+": …
```
=> fix: Parity state diff when creating SC with balance

src/tracing/types.rs
Adds a basic util on the CallTraceNode
=> feat: util method to get selector

Cargo.toml, src/tracing/builder/parity.rs, src/tracing/mod.rs, src/tracing/types.rs
=> feat: trace `position` field + bump deps

Cargo.toml, src/access_list.rs, src/opcode.rs, src/tracing/builder/geth.rs, src/tracing/builder/parity.rs, src/tracing/config.rs, src/tracing/fourbyte.rs, src/tracing/mux.rs, src/tracing/types.rs, tests/it/geth.rs, tests/it/parity.rs
Closes https://github.com/paradigmxyz/revm-inspectors/issues/188
=> chore: flatten alloy-rpc-types

src/tracing/js/mod.rs
copy tests from https://github.com/ethereum/go-ethereum/blob/fad7e74a1b2995dd79002c184e532eff31382579/eth/tracers/js/tracer_test.go#L90
=> chore(tracing/js): add more unit tests

src/tracing/builder/geth.rs, src/tracing/config.rs, src/tracing/mod.rs, src/tracing/mux.rs, tests/it/geth.rs
closes https://github.com/paradigmxyz/revm-inspectors/issues/62
=> tracing: optimize MuxTracer

src/tracing/mux.rs, tests/it/geth.rs
closes https://github.com/paradigmxyz/revm-inspectors/issues/201
BTW, this will also change the public method `try_into_mux_frame`, so need to adjust in reth's side.
=> tracing: implement FlatCallTracer

src/tracing/js/mod.rs
replaces todo! with a revert outcome return value
=> chore: remove bad todo

Cargo.toml, src/tracing/utils.rs
Bump alloy to the next version.
=> chore: bump alloy 0.11

src/access_list.rs, tests/it/accesslist.rs, tests/it/main.rs
ref https://github.com/paradigmxyz/reth/issues/15440
add one test for accesslist inspector
=> test: add accesslist tests

Cargo.toml, src/tracing/js/mod.rs
=> chore: alloy 0.14

src/access_list.rs
fixes [#15757](https://github.com/paradigmxyz/reth/issues/15757)
=> excluded valid 7702 authorities from create_accesslist

src/lib.rs, src/storage.rs
Towards [#15984](https://github.com/paradigmxyz/reth/issues/15984)
=> feat: added storageinspector

src/tracing/js/mod.rs, src/tracing/types.rs, src/tracing/utils.rs
closes #292
we previously didn't set the error field for the exit function
=> fix: set error for exit call

src/tracing/js/bindings.rs
ref https://github.com/paradigmxyz/reth/issues/13089
we should return the original bytes here
=> fix: use original bytecodes

src/access_list.rs, src/tracing/mod.rs, src/tracing/mux.rs, src/tracing/types.rs, src/tracing/writer.rs, src/transfer.rs
=> chore: Remove eof trace handlers

src/opcode.rs
fix gas accounting for call opcodes
cc @sslivkoff @rakita
=> fix: deduct call opcode gas

Cargo.toml, deny.toml
Bumps Revm to 27, Alloy to 1.2
Adds: BSD-2-Clause exception, previously approved in https://github.com/paradigmxyz/reth/blob/fcf58cb5acc2825e7c046f6741e90a8c5dab7847/deny.toml#L44
=> chore(deps): bump to revm 27, alloy 1.2

Cargo.toml, tests/it/geth.rs
ref https://github.com/paradigmxyz/reth/issues/17255
=> test: add top call revert test

src/tracing/config.rs
=> feat: add erc7562 config

src/edge_cov.rs
Minimize the impact of `fn step` for the common case of not doing anything.
=> perf: outline edgecov step fn

src/tracing/builder/geth.rs
Covering few edge cases on memory copy.
=> fix(geth_tracer): keccak input edge cases

src/tracing/js/builtins.rs
ref 
https://github.com/paradigmxyz/reth/issues/16289
we need to patch uneven js input strings, which could be digits, this now behaves like geth's tracer
https://github.com/ethereum/go-ethereum/blob/355228b011ef9a85ebc0f21e7196f892038d49f0/common/bytes.go#L27-L37
https://github.com/ethereum/go-ethereum/blob/355228b011ef9a85ebc0f21e7196f892038d49f0/eth/tracers/js/goja.go#L91-L91
=> fix: allow single digit hex strings

src/tracing/builder/geth.rs
=> chore: use hashmap default

src/tracing/mod.rs
smol thing I found while looking at
https://github.com/paradigmxyz/reth/discussions/17629
=> chore: rm log clone

src/edge_cov.rs
Fixes: https://github.com/paradigmxyz/revm-inspectors/actions/runs/17609870312/job/50029106190?pr=347
=> fix(`ci`): feature checks failing due to `std::` use

.github/SECURITY.md
Currently missing from the repo
=> chore: add `SECURITY.md`

src/tracing/builder/geth.rs, src/tracing/mod.rs, src/tracing/types.rs
=> chore: Remove depth and contract fields from CallTraceStep
